check if the subprocess has started when __del__ is called
this fix avoids getting the "AttributeError: 'Client64 subclass' object has no attribute '_proc'" when the __del__ method is called and an exception was raised before the code got to the subprocess.Popen call